### ISSUE TITLE
feat: Bridge import available balance to the input amount

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/RealmsWorld#109]
### Describe the feature you'd like to request

Under the bridge tab.

It would be simpler for a user to be able to click the "available balance" amount and it fill the total amount into the "from" amount.

<img width="549" alt="Screenshot 2024-02-01 at 18 16 34" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/114863662/125e5033-4d58-4326-9568-3837c7b31d38">

### Describe the solution you'd like to see

When clicking the "available amount" number it import the total amount into the input field for bridging.

**Comment by ponderingdemocritus** [comment]
closed in #141
