### ISSUE TITLE
feat: Show value in ETH or USD within Marketplace

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/RealmsWorld#114]
### Describe the feature you'd like to request

Currently the marketplace **only** shows $LORDS value. It would be useful to show the price in ETH also.

<img width="1564" alt="Screenshot 2024-02-06 at 13 52 53" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/114863662/0677ec9b-1003-4f5b-8f6b-0a80f5385833">

### Describe the solution you'd like to see

Having a conversion showing of the value of an NFT in ETH will be useful for the end user.

Example -
<img width="1585" alt="Screenshot 2024-02-06 at 13 56 45" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/114863662/c9262c11-9220-402b-9a64-57d2ac1f1e9e">

**Comment by blackmirrordesigner** [comment]
<img width="1728" alt="Screenshot 2024-03-07 at 14 19 29" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/91994843/716c2dd4-af82-485d-b2b4-f0bc785800a8">
check it out now, ser calc

**Comment by Calcutatator** [comment]
Cant seem to see any difference in my UI still
<img width="1556" alt="Screenshot 2024-03-07 at 15 26 26" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/114863662/0984454b-48fb-4f5b-86b3-203658d1e782">

**Comment by RedBeardEth** [comment]
added in #194
