### ISSUE TITLE
Multi-trait searches on collections don't work

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/RealmsWorld#129]
### Provide environment information

1. What

### Describe the bug

Selecting two traits in a collection results in zero items appearing eg magical beast and tier 1

### Link to reproduction

https://realms.world/collection/beasts?type=Magical&tier=1

### To reproduce

- Go to a collection (beasts)
- Select two traits that you know will be relevant eg magical, tier 4

**Comment by tenoxious** [comment]
@LordSquiddy this should be fixed with https://github.com/BibliothecaDAO/RealmsWorld/pull/155
