### ISSUE TITLE
feat: Add number of unique holders to the staking page

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/RealmsWorld#157]
### Describe the feature you'd like to request

Would be good to have the number of unique Realms holders to the staking page (currently only viewable on https://dune.com/redbeard/Realms-(for-Adventurers)-NFT which is currently not showing the figure)

### Describe the solution you'd like to see

Adding this to the data block

![image](https://github.com/BibliothecaDAO/RealmsWorld/assets/91049656/392b99c8-eabf-4716-a532-e6680f5913ea)

**Comment by Oshioke-Salaki** [comment]
Please can i be assigned this. I would handle this ASAP

**Comment by RedBeardEth** [comment]
Closing as move to l2 bridge imminent
