### ISSUE TITLE
Studio Page

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/RealmsWorld#193]
With the many studios now appearing on Realms World, it make sense to include a Studio page, where users can navigate these studios games/assets.

Features:

- [x] Studio details (this would be another JSON data structure)
- [x] Games made/playable
- [ ] Metrics of onchain revenue by studios
- [ ] Open positions - if any

**Comment by Xaxxoo** [comment]
@ponderingdemocritus Could you please assign this to me? Thank you.
