### ISSUE TITLE
bug: Coingecko Link directs to Coinmarketcap

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/RealmsWorld#196]
### Provide environment information

Irrelevant

### Describe the bug

The Coingecko link is incorrectly linking to Coinmarketcap
<img width="616" alt="Screenshot 2024-04-05 at 01 22 17" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/114863662/59bb0c68-5b68-4600-b241-2ad7f82d5426">

### Link to reproduction

https://realms.world/tokenomics

### To reproduce

Click the Coingecko link on https://realms.world/tokenomics

**Comment by EjembiEmmanuel** [comment]
@Calcutatator please I would love to contribute to this
