### ISSUE TITLE
bug: typo on L3 page

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#201]
### Provide environment information

please delete 'dojo' at end of second paragraph on L3 page

<img width="644" alt="image" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/102318873/aa4e791f-58f6-4974-a3dd-23b084b3b544">

### Describe the bug

typo

### Link to reproduction

typo

### To reproduce

typo

**Comment by EmmanuelAR** [comment]
Hey @LordSecretive, would it be possible for me to work on this issue?
