### ISSUE TITLE
feat: Add the Lords token swap to marketplace 

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaDAO/RealmsWorld#207]
### Describe the feature you'd like to request

When purchasing items in the L2 marketplace - there should be an easy option to purchase LORDS if current account balance is insufficient

### Describe the solution you'd like to see

On the marketplace purchase modal - if the user does not have enough LORDS they should be able to click one button to pull up a swap modal with the Lords balance required prefilled

**Comment by bhavyagosai** [comment]
Hey this looks like an interesting ux feature! Can I be assigned on it if it's up for grabs? Thank you

**Comment by BlackStarkGoku** [comment]
Hello, I am a Nextjs, typescript software engineer that just started contributing to this wonderful ecosystem! I already did my first contributions on other projects and saw this one via ODhack that could be interesting.
I would suggest to use the mechanic of intercepting routes from Nextjs as I saw on the website that a "/swap" route already exists. When clicking on a button If there is not enough LORDS, we can put the "/swap" route on a modal that will allow them to easily purchase!
Would love to be assigned :)

**Comment by kateberryd** [comment]
Hi @RedBeardEth I would love to work on this

**Comment by Ugo-X** [comment]
hello, @RedBeardEth my name is Ugo,  I love what y'all are building, and i would love to contribute to the effort. Please can i be assigned this task?

**Comment by Ugo-X** [comment]
hello, @RedBeardEth my name is Ugo, I love what y'all are building, and i would love to contribute to the effort. Please can i be assigned this task?
