### ISSUE TITLE
Realms World Update

### ISSUE THREAD

**Issue by Cumberlord** [BibliothecaDAO/RealmsWorld#226]
### Describe the feature you'd like to request

Update PAVED page

### Describe the solution you'd like to see

Change homepage link address to: https://sepolia.paved.gg/
Change 'chain' to: Sepolia

**Comment by EmmanuelAR** [comment]
Hey I make the change in this pr https://github.com/BibliothecaDAO/RealmsWorld/pull/227
Will be a pleassure to me to work on this projec, please let me know! @Cumberlord

**Comment by devcollinss** [comment]
Can I be assigned this issue? I will deliver ASAP

**Comment by EmmanuelAR** [comment]
Hey @Cumberlord any update on this? I attached the pr in the comments, nice weekend!
