### ISSUE TITLE
bug: Spelling error on delegated realms profile section

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/RealmsWorld#248]
### Provide environment information

MAC OS Chrome @ realms.world/account/delegates

### Describe the bug

<img width="251" alt="Screenshot 2024-08-05 at 14 03 36" src="https://github.com/user-attachments/assets/91e0ecbc-8610-4d1b-983e-75c53d617f6a">

The text for "Delegated" is misspelt as "Delgated"

### Link to reproduction

https://realms.world/account/delegates

### To reproduce

https://realms.world/account/delegates

**Comment by RedBeardEth** [comment]
Fixed in #249
