### ISSUE TITLE
Manage multiple veLORDS positions from one wallet

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#283]
### Describe the feature you'd like to request

The ability to manage multiple veLORDS positions in one wallet from the Lords account page

### Describe the solution you'd like to see

The ability to manage multiple veLORDS positions in one wallet from the Lords account page

**Comment by RedBeardEth** [comment]
I don't believe this is possible with the implementation of the contract (each address can only have one lock - similar to Yearn veYFI) - and would likely take substantial refactoring to support
