### ISSUE TITLE
bug: Blobert listing bugged

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/RealmsWorld#287]
### Provide environment information

mas os chrome

### Describe the bug

The below Blobert has broke, I do believe this is due to someone listing in ETH. Can this be cleared please.

<img width="1378" alt="Screenshot 2024-09-20 at 12 23 35" src="https://github.com/user-attachments/assets/444aedda-d362-416f-a896-cf120e022edd">

### To reproduce

Go to: https://market.realms.world/collection/0x00539f522b29ae9251dbf7443c7a950cf260372e69efab3710a11bf17a9599f1

**Comment by ShantelPeters** [comment]
Kindly assign

**Comment by devcollinss** [comment]
Hi @Calcutatator, I can work on this issue. Could you please assign it to me?

**Comment by MartianGreed** [comment]
Fixed on marketplace there : https://github.com/BibliothecaDAO/market/commit/0a7b3000f326495335bdefa279ea39d9bfe3cf53
