### ISSUE TITLE
feat: change font for numbers on Empire.Realms.World

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#306]
### Describe the feature you'd like to request

feat: change font for numbers on Empire.Realms.World

it's a nice font, but the zero like like an 8

native english speakers probably fine, but asian audience will really not like

<img width="700" alt="image" src="https://github.com/user-attachments/assets/805cb880-2bf2-43b7-bbb8-a0c9e16c5b73">

### Describe the solution you'd like to see

simple font for numbers in tables

**Comment by RedBeardEth** [comment]
Fixed in https://github.com/BibliothecaDAO/eternum/pull/2234
