### ISSUE TITLE
feat: on Empire.Realms.World - ADD THESE LINKS TO SIDEBAR TO ASSIST FLOW OF USER + GAME LAUNCH BUTTON

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#309]
### Describe the feature you'd like to request

**Links to go into sidebar - to open new tabs**

Market
https://market.realms.world/collection/0x057675b9c0bd62b096a2e15502a37b290fa766ead21c33eda42993e48a714b80

Documentation
https://eternum-docs.realms.world/

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/1284cef2-a3b6-4788-a28d-54ff8f09490f">

**GAME LAUNCH BUTTON - top right corner, exciting looking**

[LAUNCH ETERNUM]

### Describe the solution you'd like to see

.

**Comment by RedBeardEth** [comment]
Fixed in https://github.com/BibliothecaDAO/eternum/pull/2234
