### ISSUE TITLE
bug: Loot Survivor link outdated

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/RealmsWorld#53]
### Provide environment information

Mac 2017 - Chrome

### Describe the bug

The Loot Survivor Loot Survivor link on the main Realms.World page gives error 404 goes to (https://realms.world/games/loot-survivor)

This needs updating to survivor.realms.world.

<img width="1029" alt="Screenshot 2023-11-09 at 23 40 35" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/114863662/3de0388d-a7be-4c2d-a68d-180cc1d7952d">

### Link to reproduction

realms.world

### To reproduce

Press the Loot Survivor on the main realms.world page

**Comment by RedBeardEth** [comment]
Fixed in  3f79a3c
