### ISSUE TITLE
Include $LORDS to the website

### ISSUE THREAD

**Issue by GrugLikesRocks** [BibliothecaDAO/RealmsWorld#57]
### Describe the feature you'd like to request

There is currently no trace of $LORDS mentioned on our website. I believe we should add it as well as few links on where to trade it

### Describe the solution you'd like to see

Perhaps the price can be added just below the Realms.World logo on the left menu

**Comment by Calcutatator** [comment]
A few useful links, the main ones- 

AVNU TRADING (L2): https://app.avnu.fi/en?tokenFrom=0x124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49&tokenTo=0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7&amount=10000

EKUBO POOL: https://app.ekubo.org/charts/LORDS/ETH

L1 TRADING: https://dexscreener.com/ethereum/0x5104846dc1c3c7697b856dc69e350ae4dcc47e24
