### ISSUE TITLE
bug: Bridge transaction list

### ISSUE THREAD

**Issue by gogibear** [BibliothecaDAO/RealmsWorld#69]
### Provide environment information

MacOS
Brave Browser

### Describe the bug

Is the bridge transaction list supposed to have withdrawals under the starknet column? Maybe it is not I see all my tx under mainnet have a red or green symbol which could mean deposit and withdrawal. Wondering what the starknet column is meant for then.

### Link to reproduction

https://realms.world/bridge?action=withdraw

### To reproduce

<img width="715" alt="Screenshot 2023-12-01 at 3 30 58 PM" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/102257289/2ae90419-9698-46f8-9c3f-d3de7ac6c6f7">

Click bridge and then link your wallets.

**Comment by RedBeardEth** [comment]
Should be fixed now in ed2aef3
