### ISSUE TITLE
bug: Beasts collected don't show on Realms.World when collected = 404

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#77]
### Provide environment information

.

### Describe the bug

appears after a few mins, but initially 404

https://realms.world/collection/beasts/405

### Link to reproduction

https://realms.world/collection/beasts/405

### To reproduce

kill a beast

### Additional information

.

**Comment by RedBeardEth** [comment]
Have now added a fallback mechanism in ed2aef3 which will fetch metadata directly from the contract if it doesnt exist on the indexer
