### ISSUE TITLE
Golden token not displaying on R.W user page

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#78]
![image](https://github.com/BibliothecaDAO/RealmsWorld/assets/102318873/27325689-f720-4754-8366-c8182c639dec)

https://realms.world/user/0x01f447b1d086c66533b481311813a68cde116aacf39fb9611636f18c79502241/beasts

**Comment by RedBeardEth** [comment]
Is this in relation to the beast metadata not showing (406) or the golden token (in the separate tab up the top -accesible at URL https://realms.world/user/0x01f447b1d086c66533b481311813a68cde116aacf39fb9611636f18c79502241)

**Comment by LordSecretive** [comment]
I realise my mistake....

in the screengrab in the frame for #406 I though it was where my golden ticket would be displayed. I realise not it was a beast that was not displaying.  Apologies for the confusion. I checked now and the beast displays as expected
